import { Recipe } from "@/lib/types";
import { generateId } from "@/lib/recipe-utils";

export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: generateId(),
    title: "Classic Chocolate Chip Cookies",
    description:
      "Soft, chewy, and loaded with chocolate chips - the perfect comfort cookie",
    category: "Dessert",
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    ingredients: [
      {
        id: generateId(),
        name: "all-purpose flour",
        amount: "2¼",
        unit: "cups",
      },
      { id: generateId(), name: "baking soda", amount: "1", unit: "tsp" },
      { id: generateId(), name: "salt", amount: "1", unit: "tsp" },
      { id: generateId(), name: "butter, softened", amount: "1", unit: "cup" },
      { id: generateId(), name: "granulated sugar", amount: "¾", unit: "cup" },
      {
        id: generateId(),
        name: "brown sugar, packed",
        amount: "¾",
        unit: "cup",
      },
      { id: generateId(), name: "large eggs", amount: "2", unit: "" },
      { id: generateId(), name: "vanilla extract", amount: "2", unit: "tsp" },
      { id: generateId(), name: "chocolate chips", amount: "2", unit: "cups" },
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line baking sheets with parchment paper.",
      "In a medium bowl, whisk together flour, baking soda, and salt. Set aside.",
      "In a large bowl, cream together softened butter, granulated sugar, and brown sugar until light and fluffy, about 3-4 minutes.",
      "Beat in eggs one at a time, then stir in vanilla extract.",
      "Gradually mix in the flour mixture until just combined. Don't overmix.",
      "Fold in chocolate chips until evenly distributed.",
      "Drop rounded tablespoons of dough onto prepared baking sheets, spacing them about 2 inches apart.",
      "Bake for 9-11 minutes, or until edges are golden brown but centers still look soft.",
      "Cool on baking sheet for 5 minutes before transferring to a wire rack.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Creamy Mushroom Risotto",
    description:
      "Rich and creamy Arborio rice with earthy mushrooms and Parmesan",
    category: "Dinner",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    ingredients: [
      { id: generateId(), name: "Arborio rice", amount: "1½", unit: "cups" },
      {
        id: generateId(),
        name: "vegetable or chicken broth",
        amount: "6",
        unit: "cups",
      },
      {
        id: generateId(),
        name: "mixed mushrooms, sliced",
        amount: "8",
        unit: "oz",
      },
      { id: generateId(), name: "onion, diced", amount: "1", unit: "medium" },
      {
        id: generateId(),
        name: "garlic cloves, minced",
        amount: "3",
        unit: "",
      },
      { id: generateId(), name: "white wine", amount: "½", unit: "cup" },
      { id: generateId(), name: "butter", amount: "4", unit: "tbsp" },
      { id: generateId(), name: "olive oil", amount: "2", unit: "tbsp" },
      {
        id: generateId(),
        name: "Parmesan cheese, grated",
        amount: "¾",
        unit: "cup",
      },
      { id: generateId(), name: "fresh thyme", amount: "2", unit: "tsp" },
      {
        id: generateId(),
        name: "salt and pepper",
        amount: "to",
        unit: "taste",
      },
    ],
    instructions: [
      "Heat broth in a saucepan and keep warm on low heat throughout cooking.",
      "In a large skillet, heat 1 tbsp olive oil and sauté mushrooms until golden. Season with salt and pepper. Set aside.",
      "In the same pan, heat remaining oil and 1 tbsp butter. Add onion and cook until translucent, about 3-4 minutes.",
      "Add garlic and cook for another minute until fragrant.",
      "Add Arborio rice and stir to coat with oil. Toast for 2-3 minutes until edges become translucent.",
      "Pour in white wine and stir until absorbed.",
      "Add warm broth one ladle at a time, stirring constantly. Wait until each addition is absorbed before adding more.",
      "Continue this process for 18-20 minutes until rice is creamy but still has a slight bite.",
      "Stir in cooked mushrooms, remaining butter, Parmesan, and thyme.",
      "Season with salt and pepper to taste. Serve immediately while hot and creamy.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Fresh Berry Smoothie Bowl",
    description: "A nutritious and colorful breakfast packed with antioxidants",
    category: "Breakfast",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    ingredients: [
      {
        id: generateId(),
        name: "frozen mixed berries",
        amount: "1½",
        unit: "cups",
      },
      { id: generateId(), name: "banana, sliced", amount: "1", unit: "large" },
      { id: generateId(), name: "Greek yogurt", amount: "½", unit: "cup" },
      { id: generateId(), name: "almond milk", amount: "¼", unit: "cup" },
      { id: generateId(), name: "honey", amount: "1", unit: "tbsp" },
      { id: generateId(), name: "granola", amount: "¼", unit: "cup" },
      { id: generateId(), name: "fresh berries", amount: "½", unit: "cup" },
      { id: generateId(), name: "coconut flakes", amount: "2", unit: "tbsp" },
      { id: generateId(), name: "chia seeds", amount: "1", unit: "tbsp" },
    ],
    instructions: [
      "Add frozen berries, half the banana, Greek yogurt, almond milk, and honey to a blender.",
      "Blend until smooth and thick, adding more almond milk if needed for desired consistency.",
      "Pour the smoothie mixture into two bowls.",
      "Top with remaining banana slices, fresh berries, granola, coconut flakes, and chia seeds.",
      "Serve immediately while cold and fresh.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Mediterranean Quinoa Salad",
    description:
      "A refreshing and protein-packed salad with vibrant Mediterranean flavors",
    category: "Lunch",
    prepTime: 20,
    cookTime: 15,
    servings: 6,
    ingredients: [
      { id: generateId(), name: "quinoa", amount: "1", unit: "cup" },
      { id: generateId(), name: "cucumber, diced", amount: "1", unit: "large" },
      {
        id: generateId(),
        name: "cherry tomatoes, halved",
        amount: "2",
        unit: "cups",
      },
      {
        id: generateId(),
        name: "red onion, finely diced",
        amount: "½",
        unit: "small",
      },
      {
        id: generateId(),
        name: "kalamata olives, pitted and halved",
        amount: "½",
        unit: "cup",
      },
      {
        id: generateId(),
        name: "feta cheese, crumbled",
        amount: "¾",
        unit: "cup",
      },
      {
        id: generateId(),
        name: "fresh parsley, chopped",
        amount: "¼",
        unit: "cup",
      },
      {
        id: generateId(),
        name: "fresh mint, chopped",
        amount: "2",
        unit: "tbsp",
      },
      { id: generateId(), name: "lemon juice", amount: "3", unit: "tbsp" },
      {
        id: generateId(),
        name: "extra virgin olive oil",
        amount: "3",
        unit: "tbsp",
      },
      { id: generateId(), name: "dried oregano", amount: "1", unit: "tsp" },
      {
        id: generateId(),
        name: "salt and pepper",
        amount: "to",
        unit: "taste",
      },
    ],
    instructions: [
      "Rinse quinoa in cold water. Combine with 2 cups water in a saucepan and bring to a boil.",
      "Reduce heat to low, cover, and simmer for 15 minutes until water is absorbed.",
      "Remove from heat and let stand 5 minutes. Fluff with a fork and cool completely.",
      "While quinoa cools, prepare vegetables: dice cucumber and red onion, halve tomatoes and olives.",
      "In a small bowl, whisk together lemon juice, olive oil, oregano, salt, and pepper.",
      "In a large bowl, combine cooled quinoa, cucumber, tomatoes, red onion, and olives.",
      "Pour dressing over the salad and toss to combine.",
      "Add feta cheese, parsley, and mint. Gently fold to distribute.",
      "Taste and adjust seasoning. Chill for at least 30 minutes before serving.",
      "Can be made up to 2 days ahead and stored in refrigerator.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Thai Green Curry with Chicken",
    description:
      "Aromatic and spicy Thai curry with tender chicken and fresh vegetables",
    category: "Dinner",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    ingredients: [
      {
        id: generateId(),
        name: "boneless chicken thighs, sliced",
        amount: "1",
        unit: "lb",
      },
      {
        id: generateId(),
        name: "coconut milk",
        amount: "1",
        unit: "can (14 oz)",
      },
      {
        id: generateId(),
        name: "green curry paste",
        amount: "2-3",
        unit: "tbsp",
      },
      { id: generateId(), name: "fish sauce", amount: "2", unit: "tbsp" },
      { id: generateId(), name: "brown sugar", amount: "1", unit: "tbsp" },
      {
        id: generateId(),
        name: "Thai eggplant, quartered",
        amount: "2",
        unit: "small",
      },
      {
        id: generateId(),
        name: "bell pepper, sliced",
        amount: "1",
        unit: "red",
      },
      {
        id: generateId(),
        name: "bamboo shoots, drained",
        amount: "½",
        unit: "cup",
      },
      { id: generateId(), name: "Thai basil leaves", amount: "¼", unit: "cup" },
      { id: generateId(), name: "lime juice", amount: "2", unit: "tbsp" },
      {
        id: generateId(),
        name: "jasmine rice",
        amount: "2",
        unit: "cups cooked",
      },
    ],
    instructions: [
      "Heat 2 tablespoons of thick coconut cream from the top of the can in a wok over medium-high heat.",
      "Add green curry paste and fry for 2-3 minutes until fragrant.",
      "Add chicken pieces and cook for 5-6 minutes until no longer pink.",
      "Pour in remaining coconut milk, fish sauce, and brown sugar. Bring to a gentle boil.",
      "Add eggplant and simmer for 10 minutes until tender.",
      "Add bell pepper and bamboo shoots. Cook for 3-4 minutes until pepper is crisp-tender.",
      "Remove from heat and stir in Thai basil and lime juice.",
      "Taste and adjust seasoning with more fish sauce, sugar, or curry paste as needed.",
      "Serve immediately over jasmine rice, garnished with extra basil leaves.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Fluffy Pancakes",
    description:
      "Light, airy pancakes perfect for weekend breakfast with maple syrup",
    category: "Breakfast",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    ingredients: [
      {
        id: generateId(),
        name: "all-purpose flour",
        amount: "2",
        unit: "cups",
      },
      { id: generateId(), name: "baking powder", amount: "2", unit: "tsp" },
      { id: generateId(), name: "salt", amount: "½", unit: "tsp" },
      { id: generateId(), name: "sugar", amount: "2", unit: "tbsp" },
      { id: generateId(), name: "large eggs", amount: "2", unit: "" },
      { id: generateId(), name: "milk", amount: "1¾", unit: "cups" },
      { id: generateId(), name: "melted butter", amount: "¼", unit: "cup" },
      { id: generateId(), name: "vanilla extract", amount: "1", unit: "tsp" },
      {
        id: generateId(),
        name: "butter for cooking",
        amount: "as",
        unit: "needed",
      },
    ],
    instructions: [
      "In a large bowl, whisk together flour, baking powder, salt, and sugar.",
      "In another bowl, whisk eggs, then add milk, melted butter, and vanilla.",
      "Pour wet ingredients into dry ingredients and stir until just combined. Don't overmix - lumps are okay.",
      "Let batter rest for 5 minutes while heating the pan.",
      "Heat a non-stick pan or griddle over medium heat. Add a little butter.",
      "Pour ¼ cup of batter for each pancake onto the hot surface.",
      "Cook until bubbles form on surface and edges look set, about 2-3 minutes.",
      "Flip and cook until golden brown on the other side, about 1-2 minutes more.",
      "Serve immediately with butter and maple syrup, or keep warm in a 200°F oven.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Caesar Salad with Homemade Croutons",
    description:
      "Classic Caesar salad with crispy romaine, parmesan, and golden croutons",
    category: "Lunch",
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    ingredients: [
      {
        id: generateId(),
        name: "romaine lettuce, chopped",
        amount: "2",
        unit: "large heads",
      },
      {
        id: generateId(),
        name: "Parmesan cheese, grated",
        amount: "¾",
        unit: "cup",
      },
      {
        id: generateId(),
        name: "day-old bread, cubed",
        amount: "3",
        unit: "cups",
      },
      { id: generateId(), name: "olive oil", amount: "3", unit: "tbsp" },
      {
        id: generateId(),
        name: "garlic cloves, minced",
        amount: "2",
        unit: "",
      },
      { id: generateId(), name: "mayonnaise", amount: "½", unit: "cup" },
      { id: generateId(), name: "lemon juice", amount: "2", unit: "tbsp" },
      {
        id: generateId(),
        name: "Worcestershire sauce",
        amount: "1",
        unit: "tsp",
      },
      { id: generateId(), name: "Dijon mustard", amount: "1", unit: "tsp" },
      { id: generateId(), name: "anchovy paste", amount: "1", unit: "tsp" },
      { id: generateId(), name: "black pepper", amount: "½", unit: "tsp" },
    ],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Toss bread cubes with 2 tbsp olive oil and half the minced garlic. Season with salt.",
      "Spread on a baking sheet and bake for 8-10 minutes until golden and crispy.",
      "For dressing, whisk together mayonnaise, lemon juice, remaining garlic, Worcestershire, mustard, and anchovy paste.",
      "Season dressing with black pepper and mix until smooth.",
      "Wash and dry romaine lettuce thoroughly. Chop into bite-sized pieces.",
      "In a large bowl, toss lettuce with dressing until well coated.",
      "Add half the Parmesan cheese and toss again.",
      "Top with croutons and remaining Parmesan cheese.",
      "Serve immediately while croutons are still crispy.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Beef Tacos with Fresh Salsa",
    description:
      "Juicy seasoned ground beef tacos topped with vibrant homemade salsa",
    category: "Dinner",
    prepTime: 20,
    cookTime: 15,
    servings: 6,
    ingredients: [
      { id: generateId(), name: "ground beef", amount: "1", unit: "lb" },
      { id: generateId(), name: "taco seasoning", amount: "1", unit: "packet" },
      { id: generateId(), name: "water", amount: "¾", unit: "cup" },
      { id: generateId(), name: "corn tortillas", amount: "12", unit: "small" },
      {
        id: generateId(),
        name: "tomatoes, diced",
        amount: "3",
        unit: "medium",
      },
      {
        id: generateId(),
        name: "white onion, finely diced",
        amount: "½",
        unit: "small",
      },
      { id: generateId(), name: "jalapeño, minced", amount: "1", unit: "" },
      {
        id: generateId(),
        name: "fresh cilantro, chopped",
        amount: "¼",
        unit: "cup",
      },
      { id: generateId(), name: "lime juice", amount: "2", unit: "tbsp" },
      { id: generateId(), name: "shredded lettuce", amount: "2", unit: "cups" },
      {
        id: generateId(),
        name: "Mexican cheese blend",
        amount: "1",
        unit: "cup",
      },
      { id: generateId(), name: "sour cream", amount: "½", unit: "cup" },
    ],
    instructions: [
      "For salsa, combine diced tomatoes, onion, jalapeño, cilantro, and lime juice in a bowl. Season with salt and set aside.",
      "Heat a large skillet over medium-high heat. Add ground beef and cook, breaking it up, until browned, about 6-8 minutes.",
      "Drain excess fat, then add taco seasoning and water. Simmer for 5 minutes until thickened.",
      "Warm tortillas in a dry skillet for 30 seconds per side, or wrap in damp paper towels and microwave for 30 seconds.",
      "Set up taco bar with warmed tortillas, seasoned beef, fresh salsa, lettuce, cheese, and sour cream.",
      "Let everyone assemble their own tacos with desired toppings.",
      "Serve with lime wedges and additional hot sauce if desired.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Lemon Bars",
    description:
      "Tangy lemon custard on a buttery shortbread crust, dusted with powdered sugar",
    category: "Dessert",
    prepTime: 15,
    cookTime: 45,
    servings: 16,
    ingredients: [
      {
        id: generateId(),
        name: "all-purpose flour",
        amount: "2",
        unit: "cups",
      },
      { id: generateId(), name: "powdered sugar", amount: "½", unit: "cup" },
      { id: generateId(), name: "salt", amount: "¼", unit: "tsp" },
      {
        id: generateId(),
        name: "cold butter, cubed",
        amount: "1",
        unit: "cup",
      },
      { id: generateId(), name: "large eggs", amount: "4", unit: "" },
      {
        id: generateId(),
        name: "granulated sugar",
        amount: "1¾",
        unit: "cups",
      },
      { id: generateId(), name: "fresh lemon juice", amount: "⅓", unit: "cup" },
      { id: generateId(), name: "lemon zest", amount: "2", unit: "tbsp" },
      {
        id: generateId(),
        name: "all-purpose flour",
        amount: "3",
        unit: "tbsp",
      },
      {
        id: generateId(),
        name: "powdered sugar for dusting",
        amount: "¼",
        unit: "cup",
      },
    ],
    instructions: [
      "Preheat oven to 350°F (175°C). Line a 9x13 inch pan with parchment paper.",
      "For crust, combine 2 cups flour, ½ cup powdered sugar, and salt in a bowl.",
      "Cut in cold butter until mixture resembles coarse crumbs.",
      "Press mixture firmly into prepared pan. Bake for 18-20 minutes until lightly golden.",
      "Meanwhile, whisk eggs and granulated sugar until smooth.",
      "Add lemon juice, lemon zest, and 3 tbsp flour. Whisk until well combined.",
      "Pour lemon mixture over hot crust and return to oven.",
      "Bake for 22-25 minutes until filling is set and lightly golden on top.",
      "Cool completely in pan, then dust with powdered sugar.",
      "Cut into squares and serve. Store covered in refrigerator.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Caprese Grilled Cheese",
    description:
      "Elevated grilled cheese with fresh mozzarella, tomatoes, and basil",
    category: "Lunch",
    prepTime: 10,
    cookTime: 8,
    servings: 2,
    ingredients: [
      {
        id: generateId(),
        name: "sourdough bread",
        amount: "4",
        unit: "slices",
      },
      {
        id: generateId(),
        name: "fresh mozzarella, sliced",
        amount: "4",
        unit: "oz",
      },
      { id: generateId(), name: "large tomato, sliced", amount: "1", unit: "" },
      { id: generateId(), name: "fresh basil leaves", amount: "8", unit: "" },
      { id: generateId(), name: "butter, softened", amount: "2", unit: "tbsp" },
      { id: generateId(), name: "balsamic glaze", amount: "1", unit: "tbsp" },
      {
        id: generateId(),
        name: "salt and pepper",
        amount: "to",
        unit: "taste",
      },
    ],
    instructions: [
      "Slice tomato into ¼-inch thick rounds and season with salt and pepper. Let drain on paper towels for 5 minutes.",
      "Butter one side of each bread slice.",
      "On the unbuttered side of two slices, layer mozzarella, tomato slices, and basil leaves.",
      "Drizzle with balsamic glaze, then top with remaining bread slices, buttered side up.",
      "Heat a skillet over medium-low heat.",
      "Cook sandwiches for 3-4 minutes per side, pressing gently, until golden brown and cheese melts.",
      "Let cool for 1 minute before cutting diagonally.",
      "Serve immediately while cheese is still melty.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Honey Garlic Salmon",
    description:
      "Perfectly glazed salmon with a sweet and savory honey garlic sauce",
    category: "Dinner",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    ingredients: [
      {
        id: generateId(),
        name: "salmon fillets",
        amount: "4",
        unit: "6 oz each",
      },
      { id: generateId(), name: "honey", amount: "¼", unit: "cup" },
      { id: generateId(), name: "soy sauce", amount: "3", unit: "tbsp" },
      {
        id: generateId(),
        name: "garlic cloves, minced",
        amount: "4",
        unit: "",
      },
      {
        id: generateId(),
        name: "fresh ginger, grated",
        amount: "1",
        unit: "tbsp",
      },
      { id: generateId(), name: "rice vinegar", amount: "2", unit: "tbsp" },
      { id: generateId(), name: "sesame oil", amount: "1", unit: "tsp" },
      { id: generateId(), name: "red pepper flakes", amount: "¼", unit: "tsp" },
      { id: generateId(), name: "green onions, sliced", amount: "2", unit: "" },
      { id: generateId(), name: "sesame seeds", amount: "1", unit: "tbsp" },
      { id: generateId(), name: "olive oil", amount: "2", unit: "tbsp" },
    ],
    instructions: [
      "Pat salmon fillets dry and season with salt and pepper.",
      "In a small bowl, whisk together honey, soy sauce, garlic, ginger, rice vinegar, sesame oil, and red pepper flakes.",
      "Heat olive oil in a large oven-safe skillet over medium-high heat.",
      "Add salmon skin-side up and cook for 4-5 minutes until golden brown.",
      "Flip salmon and pour honey garlic sauce around the fillets.",
      "Cook for 3-4 minutes more, spooning sauce over salmon frequently.",
      "If salmon needs more cooking, transfer skillet to 400°F oven for 2-3 minutes.",
      "Remove from heat and let rest for 2 minutes.",
      "Garnish with sliced green onions and sesame seeds before serving.",
      "Serve with steamed rice and vegetables.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Avocado Toast with Poached Egg",
    description:
      "Creamy avocado on crispy sourdough topped with a perfectly poached egg",
    category: "Breakfast",
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    ingredients: [
      {
        id: generateId(),
        name: "sourdough bread",
        amount: "2",
        unit: "thick slices",
      },
      { id: generateId(), name: "ripe avocados", amount: "1", unit: "large" },
      { id: generateId(), name: "large eggs", amount: "2", unit: "" },
      { id: generateId(), name: "lemon juice", amount: "1", unit: "tbsp" },
      {
        id: generateId(),
        name: "extra virgin olive oil",
        amount: "1",
        unit: "tbsp",
      },
      {
        id: generateId(),
        name: "red pepper flakes",
        amount: "pinch",
        unit: "",
      },
      { id: generateId(), name: "sea salt", amount: "to", unit: "taste" },
      { id: generateId(), name: "black pepper", amount: "to", unit: "taste" },
      { id: generateId(), name: "white vinegar", amount: "1", unit: "tbsp" },
    ],
    instructions: [
      "Fill a medium saucepan with water and bring to a gentle simmer. Add white vinegar.",
      "Toast sourdough bread until golden brown and crispy.",
      "While bread toasts, mash avocado with lemon juice, salt, and pepper until creamy but still chunky.",
      "Crack each egg into a small bowl. Create a whirlpool in the simmering water with a spoon.",
      "Gently slide one egg into the center of the whirlpool. Repeat with second egg.",
      "Poach for 3-4 minutes for runny yolks, or longer for firmer yolks.",
      "Remove eggs with a slotted spoon and drain briefly on paper towels.",
      "Spread mashed avocado generously on toasted bread.",
      "Top each toast with a poached egg.",
      "Drizzle with olive oil, sprinkle with red pepper flakes, salt, and pepper. Serve immediately.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Chicken Noodle Soup",
    description:
      "Comforting homemade soup with tender chicken, vegetables, and egg noodles",
    category: "Soup",
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    ingredients: [
      { id: generateId(), name: "chicken breasts", amount: "1", unit: "lb" },
      { id: generateId(), name: "chicken broth", amount: "8", unit: "cups" },
      { id: generateId(), name: "egg noodles", amount: "3", unit: "cups" },
      {
        id: generateId(),
        name: "carrots, sliced",
        amount: "3",
        unit: "medium",
      },
      { id: generateId(), name: "celery stalks, diced", amount: "3", unit: "" },
      { id: generateId(), name: "onion, diced", amount: "1", unit: "medium" },
      {
        id: generateId(),
        name: "garlic cloves, minced",
        amount: "3",
        unit: "",
      },
      { id: generateId(), name: "bay leaves", amount: "2", unit: "" },
      { id: generateId(), name: "dried thyme", amount: "1", unit: "tsp" },
      {
        id: generateId(),
        name: "fresh parsley, chopped",
        amount: "¼",
        unit: "cup",
      },
      { id: generateId(), name: "olive oil", amount: "2", unit: "tbsp" },
      {
        id: generateId(),
        name: "salt and pepper",
        amount: "to",
        unit: "taste",
      },
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat. Season chicken with salt and pepper.",
      "Add chicken to pot and cook until browned on both sides, about 6-8 minutes total. Remove and set aside.",
      "In the same pot, sauté onion, carrots, and celery until softened, about 5 minutes.",
      "Add garlic and cook for another minute until fragrant.",
      "Pour in chicken broth, add bay leaves and thyme. Bring to a boil.",
      "Return chicken to pot, reduce heat, and simmer for 20-25 minutes until chicken is cooked through.",
      "Remove chicken, let cool slightly, then shred into bite-sized pieces.",
      "Bring soup back to a boil and add egg noodles. Cook according to package directions.",
      "Return shredded chicken to pot and simmer for 2-3 minutes to heat through.",
      "Remove bay leaves, stir in fresh parsley, and season with salt and pepper to taste.",
      "Serve hot with crackers or crusty bread.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Chocolate Lava Cake",
    description:
      "Individual molten chocolate cakes with gooey centers - perfect for date night",
    category: "Dessert",
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    ingredients: [
      {
        id: generateId(),
        name: "dark chocolate, chopped",
        amount: "4",
        unit: "oz",
      },
      { id: generateId(), name: "unsalted butter", amount: "4", unit: "tbsp" },
      { id: generateId(), name: "large eggs", amount: "2", unit: "" },
      { id: generateId(), name: "large egg yolks", amount: "2", unit: "" },
      { id: generateId(), name: "granulated sugar", amount: "¼", unit: "cup" },
      {
        id: generateId(),
        name: "all-purpose flour",
        amount: "2",
        unit: "tbsp",
      },
      { id: generateId(), name: "pinch of salt", amount: "1", unit: "" },
      {
        id: generateId(),
        name: "butter for ramekins",
        amount: "1",
        unit: "tbsp",
      },
      {
        id: generateId(),
        name: "cocoa powder for dusting",
        amount: "1",
        unit: "tbsp",
      },
      {
        id: generateId(),
        name: "vanilla ice cream",
        amount: "4",
        unit: "scoops",
      },
    ],
    instructions: [
      "Preheat oven to 425°F (220°C). Butter four 6-oz ramekins and dust with cocoa powder.",
      "Melt chocolate and butter in a double boiler or microwave, stirring until smooth. Let cool slightly.",
      "In a bowl, whisk whole eggs, egg yolks, and sugar until thick and pale, about 2-3 minutes.",
      "Whisk in melted chocolate mixture until combined.",
      "Fold in flour and salt until just incorporated. Don't overmix.",
      "Divide batter evenly among prepared ramekins.",
      "Place ramekins on a baking sheet and bake for 12-14 minutes.",
      "Edges should be firm but centers should still jiggle slightly when shaken.",
      "Let cool for 1 minute, then run a knife around edges to loosen.",
      "Invert each ramekin onto a plate and tap gently. Lift off ramekin.",
      "Serve immediately with vanilla ice cream and dust with powdered sugar if desired.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    title: "Greek Chicken Bowls",
    description:
      "Mediterranean-inspired bowls with marinated chicken, fresh vegetables, and tzatziki",
    category: "Lunch",
    prepTime: 25,
    cookTime: 15,
    servings: 4,
    ingredients: [
      {
        id: generateId(),
        name: "boneless chicken thighs",
        amount: "1½",
        unit: "lbs",
      },
      { id: generateId(), name: "olive oil", amount: "¼", unit: "cup" },
      { id: generateId(), name: "lemon juice", amount: "2", unit: "tbsp" },
      { id: generateId(), name: "dried oregano", amount: "2", unit: "tsp" },
      {
        id: generateId(),
        name: "garlic cloves, minced",
        amount: "3",
        unit: "",
      },
      { id: generateId(), name: "quinoa", amount: "1", unit: "cup" },
      { id: generateId(), name: "cucumber, diced", amount: "1", unit: "large" },
      {
        id: generateId(),
        name: "cherry tomatoes, halved",
        amount: "2",
        unit: "cups",
      },
      {
        id: generateId(),
        name: "red onion, thinly sliced",
        amount: "½",
        unit: "small",
      },
      { id: generateId(), name: "kalamata olives", amount: "½", unit: "cup" },
      {
        id: generateId(),
        name: "feta cheese, crumbled",
        amount: "½",
        unit: "cup",
      },
      { id: generateId(), name: "Greek yogurt", amount: "1", unit: "cup" },
      {
        id: generateId(),
        name: "fresh dill, chopped",
        amount: "2",
        unit: "tbsp",
      },
    ],
    instructions: [
      "Marinate chicken in 2 tbsp olive oil, lemon juice, oregano, and 2 minced garlic cloves for 15 minutes.",
      "Cook quinoa according to package directions. Let cool and fluff with a fork.",
      "For tzatziki, mix Greek yogurt with remaining garlic, dill, and salt to taste.",
      "Heat a grill pan or skillet over medium-high heat. Cook chicken for 6-7 minutes per side until done.",
      "Let chicken rest for 5 minutes, then slice into strips.",
      "Assemble bowls with quinoa as the base.",
      "Top with sliced chicken, cucumber, tomatoes, red onion, and olives.",
      "Sprinkle with feta cheese and drizzle with remaining olive oil.",
      "Serve with tzatziki on the side and lemon wedges for extra brightness.",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
